### ISSUE TITLE
Error opening Terminal tool window in GoLand 2020.1 EAP

### ISSUE THREAD

**Issue by Russia9** [Almighty-Alpaca/JetBrains-Discord-Integration#79] opened 2020-02-17 09:13 UTC
**To reproduce**
Open terminal tool window

**IDE information:**
```
GoLand 2020.1 EAP
Build #GO-201.5259.15, built on February 13, 2020
GoLand EAP User
Expiration date: March 14, 2020
Runtime version: 11.0.6+8-b722.2 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.5.3-arch1-1
GC: ParNew, ConcurrentMarkSweep
Memory: 725M
Cores: 4
```
 
**Stacktrace:** https://gist.github.com/Russia9/233336ee3718a9bdc333445fa8f69e15

**Comment by Almighty-Alpaca** [comment] 2020-02-20 10:19
Closing this as it's a duplicate of #77

**Closed** 2020-02-20 10:20 UTC
