### ISSUE TITLE
Exception generated when I showed diff between two classes

### ISSUE THREAD

**Issue by Machine-Maker** [Almighty-Alpaca/JetBrains-Discord-Integration#198] opened 2021-09-05 19:32 UTC
```
Access is allowed from event dispatch thread only

com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: EventQueue.isDispatchThread()=false Toolkit.getEventQueue()=com.intellij.ide.IdeEventQueue@1cfa47da
Current thread: Thread[DefaultDispatcher-worker-3,5,main] 1287219671
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,main] 1710209087
	at com.intellij.openapi.application.impl.ApplicationImpl.throwThreadAccessException(ApplicationImpl.java:1030)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:1005)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.getSelectedEditorWithProvider(FileEditorManagerImpl.java:1458)
	at com.jetbrains.rdserver.editors.BackendServerFileEditorManager.getSelectedEditorWithProvider(BackendServerFileEditorManager.kt:365)
	at com.jetbrains.rdserver.editors.BackendServerFileEditorManager.getSelectedEditor(BackendServerFileEditorManager.kt:360)
	at com.intellij.diff.editor.DiffEditorTabTitleProvider.getTitle(DiffEditorTabTitleProvider.kt:30)
	at com.intellij.diff.editor.DiffEditorTabTitleProvider.getEditorTabTitle(DiffEditorTabTitleProvider.kt:17)
	at com.intellij.openapi.fileEditor.impl.EditorTabTitleProvider.getEditorTabTitle(EditorTabTitleProvider.java:22)
	at com.intellij.openapi.fileEditor.impl.EditorTabPresentationUtil.getEditorTabTitle(EditorTabPresentationUtil.java:21)
	at com.intellij.openapi.fileEditor.impl.EditorTabPresentationUtil.getUniqueEditorTabTitle(EditorTabPresentationUtil.java:32)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.data.DataService$getData$fileUniqueName$1.invoke(DataService.kt:110)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.data.DataService$getData$fileUniqueName$1.invoke(DataService.kt:49)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.utils.AsyncKt$invokeReadAction$$inlined$suspendCoroutine$lambda$1.compute(actions.kt:80)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:841)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.utils.AsyncKt.invokeReadAction(async.kt:55)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.data.DataService.getDataInternal(DataService.kt:108)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.data.DataService$getData$3.invokeSuspend(DataService.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by InfRandomness** [comment] 2021-09-05 19:35
Duplicate of https://github.com/Almighty-Alpaca/JetBrains-Discord-Integration/issues/179

**Closed by InfRandomness** 2021-09-05 19:35 UTC
