### ISSUE TITLE
IOException in Discord Integration after closing Discord

### ISSUE THREAD

**Issue by BlockyTheDev** [Almighty-Alpaca/JetBrains-Discord-Integration#281] opened 2022-12-22 22:50 UTC
```
Unhandled exception in [StandaloneCoroutine{Cancelling}@739205c2, Dispatchers.IO]

java.io.IOException: Die Pipe wird gerade geschlossen
	at java.base/java.io.RandomAccessFile.writeBytes(Native Method)
	at java.base/java.io.RandomAccessFile.write(RandomAccessFile.java:545)
	at dev.cbyrne.kdiscordipc.core.socket.impl.WindowsSocket.write(WindowsSocket.kt:48)
	at dev.cbyrne.kdiscordipc.core.socket.handler.SocketHandler$1.invokeSuspend(SocketHandler.kt:42)
	at dev.cbyrne.kdiscordipc.core.socket.handler.SocketHandler$1.invoke(SocketHandler.kt)
	at dev.cbyrne.kdiscordipc.core.socket.handler.SocketHandler$1.invoke(SocketHandler.kt)
	at kotlinx.coroutines.flow.FlowKt__TransformKt$onEach$$inlined$unsafeTransform$1$2.emit(Emitters.kt:223)
	at kotlinx.coroutines.flow.SharedFlowImpl.collect$suspendImpl(SharedFlow.kt:383)
	at kotlinx.coroutines.flow.SharedFlowImpl$collect$1.invokeSuspend(SharedFlow.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelled}@739205c2, Dispatchers.IO]
```

**Comment by dnbln** [comment] 2023-02-05 11:55
Duplicate of #257.

**Closed by dnbln** 2023-02-05 11:55 UTC
