### ISSUE TITLE
Plugin doesn't work on macOS

### ISSUE THREAD

**Issue by JavaMaxi** [Almighty-Alpaca/JetBrains-Discord-Integration#157] opened 2021-05-13 19:56 UTC
Hey, I installed the Discord-Integration-Plugin yesterday, and today I realize that the Plugin crashes, when I start IntelliJ.

Here's the Log:
```
Unhandled exception in [StandaloneCoroutine{Cancelling}@7ea52fe7, Dispatchers.Default]

java.lang.NoClassDefFoundError: Could not initialize class com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.connection.NativeRpcConnection
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.RpcService.update(RpcService.kt:121)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.RpcService.update$default(RpcService.kt:77)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.render.RenderService$render$2.invokeSuspend(RenderService.kt:75)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

My OS is macOS Big Sur, 11.3.1

**Comment by InfRandomness** [comment] 2021-05-13 20:01
Duplicate of https://github.com/Almighty-Alpaca/JetBrains-Discord-Integration/issues/145

**Closed** 2021-05-13 21:56 UTC
Labels: area: plugin, state: duplicate, type: bug
