### ISSUE TITLE
expiation

### ISSUE THREAD

**Issue by Nikita11790** [Almighty-Alpaca/JetBrains-Discord-Integration#76] opened 2020-02-05 16:37 UTC
java.lang.AssertionError: Already disposed: Project (name=SimpleMenu Print Menu one time, containerState=DISPOSE_COMPLETED, componentStore=/Users/nikita/Documents/java stuff/SimpleMenu Print Menu one time) 
	at com.intellij.openapi.components.impl.ComponentManagerImpl.lambda$throwAlreadyDisposed$0(ComponentManagerImpl.java:153)
	at com.intellij.openapi.application.ReadAction.lambda$run$1(ReadAction.java:62)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:821)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:69)
	at com.intellij.openapi.application.ReadAction.run(ReadAction.java:62)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.throwAlreadyDisposed(ComponentManagerImpl.java:151)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.getPicoContainer(ComponentManagerImpl.java:144)
	at com.intellij.serviceContainer.PlatformComponentManagerImpl.getService(PlatformComponentManagerImpl.kt:286)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:22)
	at com.intellij.util.indexing.FileBasedIndexScanRunnableCollector.getInstance(FileBasedIndexScanRunnableCollector.java:30)
	at com.intellij.util.indexing.FileBasedIndexImpl.collectScanRootRunnables(FileBasedIndexImpl.java:2397)
	at com.intellij.util.indexing.FileBasedIndexImpl.iterateIndexableFiles(FileBasedIndexImpl.java:2390)
	at com.intellij.util.indexing.FileBasedIndexImpl.projectIndexableFiles(FileBasedIndexImpl.java:1092)
	at com.intellij.util.indexing.FileBasedIndexImpl.processValuesInScope(FileBasedIndexImpl.java:953)
	at com.intellij.util.indexing.FileBasedIndexImpl.processValues(FileBasedIndexImpl.java:852)
	at com.intellij.psi.search.FileNameIndexServiceImpl.getVirtualFilesByName(FileNameIndexServiceImpl.java:27)
	at com.intellij.psi.search.FilenameIndex.getVirtualFilesByName(FilenameIndex.java:51)
	at com.intellij.openapi.fileEditor.impl.UniqueVFilePathBuilderImpl.filesWithTheSameName(UniqueVFilePathBuilderImpl.java:131)
	at com.intellij.openapi.fileEditor.impl.UniqueVFilePathBuilderImpl.getUniqueVirtualFileNameBuilder(UniqueVFilePathBuilderImpl.java:110)
	at com.intellij.openapi.fileEditor.impl.UniqueVFilePathBuilderImpl.getUniqueVirtualFilePath(UniqueVFilePathBuilderImpl.java:70)
	at com.intellij.openapi.fileEditor.impl.UniqueVFilePathBuilderImpl.getUniqueVirtualFilePath(UniqueVFilePathBuilderImpl.java:38)
	at com.intellij.openapi.fileEditor.impl.UniqueVFilePathBuilderImpl.getUniqueVirtualFilePath(UniqueVFilePathBuilderImpl.java:44)
	at com.intellij.openapi.fileEditor.impl.EditorTabPresentationUtil.getUniqueEditorTabTitle(EditorTabPresentationUtil.java:31)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.data.FileData$uniqueName$2$1.compute(FileData.kt:44)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.data.FileData$uniqueName$2$1.compute(FileData.kt:31)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:811)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.data.FileData$uniqueName$2.invoke(FileData.kt:44)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.data.FileData$uniqueName$2.invoke(FileData.kt:31)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.dependencies.kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.data.FileData.getUniqueName(FileData.kt)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.settings.values.PresenceLine$FILE_NAME_PATH.getResult(PresenceLine.kt:61)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.settings.values.PresenceLine.get(PresenceLine.kt:72)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.renderer.Renderer$render$1.invoke(Renderer.kt:47)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.renderer.Renderer$render$1.invoke(Renderer.kt:24)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.RichPresence.<init>(RichPresence.kt:46)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.renderer.Renderer.render(Renderer.kt:40)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.renderer.FileRenderer.render(FileRenderer.kt:22)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.renderer.Renderer.render(Renderer.kt:25)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.impl.RichPresenceRenderServiceImpl$render$1.invokeSuspend(RichPresenceRenderServiceImpl.kt:93)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.dependencies.kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.dependencies.kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.dependencies.kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.dependencies.kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.dependencies.kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)

**Comment by Davoleo** [comment] 2020-02-05 19:45
Duplicate of #63

**Closed** 2020-02-15 12:04 UTC
