### ISSUE TITLE
Exception in plugin Discord Integration (1.11.0)

### ISSUE THREAD

**Issue by Alugor** [Almighty-Alpaca/JetBrains-Discord-Integration#271] opened 2022-12-20 12:20 UTC
Hey,
on my latest IntelliJ IDE Ultimate the new update ain't working.

It's throwing me this stack:

`Unhandled exception in [StandaloneCoroutine{Cancelling}@774d59df, Dispatchers.Default]

dev.cbyrne.kdiscordipc.core.error.ConnectionError$NoIPCFile: Failed to find an IPC file. Is Discord open? Is this application allowed to access temporary files?
	at dev.cbyrne.kdiscordipc.core.error.ConnectionError$NoIPCFile.<clinit>(ConnectionError.kt)
	at dev.cbyrne.kdiscordipc.core.socket.handler.SocketHandler.findIPCFile(SocketHandler.kt:95)
	at dev.cbyrne.kdiscordipc.core.socket.handler.SocketHandler.findIPCFile(SocketHandler.kt:99)
	at dev.cbyrne.kdiscordipc.core.socket.handler.SocketHandler.findIPCFile(SocketHandler.kt:99)
	at dev.cbyrne.kdiscordipc.core.socket.handler.SocketHandler.findIPCFile(SocketHandler.kt:99)
	at dev.cbyrne.kdiscordipc.core.socket.handler.SocketHandler.findIPCFile(SocketHandler.kt:99)
	at dev.cbyrne.kdiscordipc.core.socket.handler.SocketHandler.findIPCFile(SocketHandler.kt:99)
	at dev.cbyrne.kdiscordipc.core.socket.handler.SocketHandler.findIPCFile(SocketHandler.kt:99)
	at dev.cbyrne.kdiscordipc.core.socket.handler.SocketHandler.findIPCFile(SocketHandler.kt:99)
	at dev.cbyrne.kdiscordipc.core.socket.handler.SocketHandler.findIPCFile(SocketHandler.kt:99)
	at dev.cbyrne.kdiscordipc.core.socket.handler.SocketHandler.findIPCFile(SocketHandler.kt:99)
	at dev.cbyrne.kdiscordipc.core.socket.handler.SocketHandler.findIPCFile(SocketHandler.kt:99)
	at dev.cbyrne.kdiscordipc.core.socket.handler.SocketHandler.connect(SocketHandler.kt:59)
	at dev.cbyrne.kdiscordipc.KDiscordIPC.connect(KDiscordIPC.kt:83)
	at dev.cbyrne.kdiscordipc.KDiscordIPC.connect$default(KDiscordIPC.kt:76)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.connection.DiscordIpcConnection$connect$2.invokeSuspend(DiscordIpcConnection.kt:59)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelled}@774d59df, Dispatchers.Default]`

About my IDE:
IntelliJ IDEA 2022.3 (Ultimate Edition)
Build #IU-223.7571.182, built on November 29, 2022
Runtime version: 17.0.5+1-b653.14 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1004M
Cores: 8
Non-Bundled Plugins:
    com.github.copilot (1.1.38.2229)
    com.demonwav.minecraft-dev (2022.3-1.5.21)
    com.almightyalpaca.intellij.plugins.discord (1.11.0)
    zielu.gittoolbox (213.10.4)

Kotlin: 223-1.7.20-release-201-IJ7571.182

**Comment by Alugor** [comment] 2022-12-20 13:56
Another one:

`kotlin.UninitializedPropertyAccessException: lateinit property randomAccessFile has not been initialized
	at dev.cbyrne.kdiscordipc.core.socket.impl.WindowsSocket.close(WindowsSocket.kt:28)
	at dev.cbyrne.kdiscordipc.core.socket.handler.SocketHandler.disconnect(SocketHandler.kt:67)
	at dev.cbyrne.kdiscordipc.KDiscordIPC.disconnect(KDiscordIPC.kt:118)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.connection.DiscordIpcConnection.disconnectInternal(DiscordIpcConnection.kt:77)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.connection.DiscordIpcConnection.dispose(DiscordIpcConnection.kt:81)
	at com.intellij.openapi.util.ObjectTree.runWithTrace(ObjectTree.java:127)
	at com.intellij.openapi.util.ObjectTree.executeAll(ObjectTree.java:159)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:243)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:231)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.RpcService$update$1.invokeSuspend(RpcService.kt:115)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)`

**Comment by dnbln** [comment] 2022-12-20 15:05
> `Failed to find an IPC file. Is Discord open? Is this application allowed to access temporary files?`

That seems to be pretty self-explanatory, but in the case discord is actually running, you can try changing to rpc (Help > Edit Custom VM Options... and add `-Dcom.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.connection=rpc`)

The second exception looks like a result of the first one, e.g. the plugin not being able to connect to discord.

**Comment by Alugor** [comment] 2022-12-20 21:19
`java.lang.Throwable: IPC error: ErrorEventData(code=4000, message=child "activity" fails because [child "assets" fails because [child "large_text" fails because ["large_text" is not allowed to be empty]]])
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:202)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.connection.DiscordIpcConnection.onError(DiscordIpcConnection.kt:133)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.connection.DiscordIpcConnection.access$onError(DiscordIpcConnection.kt:39)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.connection.DiscordIpcConnection$ipcClient$1$1.invokeSuspend$onError(DiscordIpcConnection.kt:47)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.connection.DiscordIpcConnection$ipcClient$1$1.access$invokeSuspend$onError(DiscordIpcConnection.kt)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.connection.DiscordIpcConnection$ipcClient$1$1$2.invoke(DiscordIpcConnection.kt:47)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.connection.DiscordIpcConnection$ipcClient$1$1$2.invoke(DiscordIpcConnection.kt:47)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.connection.DiscordIpcConnection$ipcClient$1$1$invokeSuspend$$inlined$onEvent$4$1.invokeSuspend(KDiscordIPC.kt:103)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)`

**Comment by mccoderpy** [comment] 2022-12-21 07:28
> > `Failed to find an IPC file. Is Discord open? Is this application allowed to access temporary files?`
> 
> That seems to be pretty self-explanatory, but in the case discord is actually running, you can try changing to rpc (Help > Edit Custom VM Options... and add `-Dcom.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.connection=rpc`)
> 
> The second exception looks like a result of the first one, e.g. the plugin not being able to connect to discord.

Yes, I got this one (the 1st) too. But however it should be handled by the plugin

**Comment by evgfilim1** [comment] 2022-12-23 05:25
Same here. The message is self-explanatory ofc, but very annoying when I don't use Discord at the moment, the message almost forces me to open Discord or disable the plugin.

**Comment by Alugor** [comment] 2023-02-03 13:10
I still get this error on many different devices.
Is there finally a fix?

**Comment by dnbln** [comment] 2023-02-05 11:49
Closing this as a duplicate of #250.

**Closed by dnbln** 2023-02-05 11:49 UTC
