### ISSUE TITLE
Exception when disabling Rich Presence

### ISSUE THREAD

**Issue by avi12** [Almighty-Alpaca/JetBrains-Discord-Integration#293] opened 2022-12-31 21:10 UTC
Occurs when I have multiple instances of a JetBrains IDE and I uncheck Enable Rich Presence in one of them
```log
Unhandled exception in [StandaloneCoroutine{Cancelling}@6b67b9ff, Dispatchers.Default]

java.io.IOException: Stream Closed
	at java.base/java.io.RandomAccessFile.read0(Native Method)
```

**Comment by janek515** [comment] 2023-01-10 17:50
Duplicate of #275

**Closed** 2023-02-05 12:02 UTC
