### ISSUE TITLE
Stream Closed

### ISSUE THREAD

**Issue by RezaNajafianRN** [Almighty-Alpaca/JetBrains-Discord-Integration#259] opened 2022-12-07 11:15 UTC
Unhandled exception in [StandaloneCoroutine{Cancelling}@3c133db4, Dispatchers.Default]

java.io.IOException: Stream Closed
	at java.base/java.io.RandomAccessFile.read0(Native Method)
	at java.base/java.io.RandomAccessFile.read(RandomAccessFile.java:365)
	at java.base/java.io.RandomAccessFile.readInt(RandomAccessFile.java:837)
	at dev.cbyrne.kdiscordipc.core.socket.impl.WindowsSocket.read(WindowsSocket.kt:38)
	at dev.cbyrne.kdiscordipc.core.socket.handler.SocketHandler$events$1.invokeSuspend(SocketHandler.kt:35)
	at dev.cbyrne.kdiscordipc.core.socket.handler.SocketHandler$events$1.invoke(SocketHandler.kt)
	at dev.cbyrne.kdiscordipc.core.socket.handler.SocketHandler$events$1.invoke(SocketHandler.kt)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
	at kotlinx.coroutines.flow.internal.ChannelFlowOperatorImpl.flowCollect(ChannelFlow.kt:195)
	at kotlinx.coroutines.flow.internal.ChannelFlowOperator.collectTo$suspendImpl(ChannelFlow.kt:157)
	at kotlinx.coroutines.flow.internal.ChannelFlowOperator.collectTo(ChannelFlow.kt)
	at kotlinx.coroutines.flow.internal.ChannelFlow$collectToFun$1.invokeSuspend(ChannelFlow.kt:60)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelled}@3c133db4, Dispatchers.Default]

**Comment by dnbln** [comment] 2023-02-05 12:03
Closing this as duplicate of #257.

**Closed by dnbln** 2023-02-05 12:03 UTC
