### ISSUE TITLE
Exception at startup on 2020.1

### ISSUE THREAD

**Issue by youssefhabri** [Almighty-Alpaca/JetBrains-Discord-Integration#77] opened 2020-02-10 18:27 UTC
```
CLion 2020.1 EAP
Build #CL-201.4865.10, built on February 4, 2020
CLion EAP User
Expiration date: March 5, 2020
Runtime version: 11.0.6+8-b702.1 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.4.17-1-manjaro
```

```
Should be called at least in the state COMPONENTS_LOADED, the current state is: CONFIGURATION_STORE_INITIALIZED
Current violators count: 1



java.lang.Throwable
	at com.intellij.diagnostic.LoadingState.logStateError(LoadingState.java:56)
	at com.intellij.diagnostic.LoadingState.checkOccurred(LoadingState.java:52)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.<init>(ActionManagerImpl.java:150)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:48)
	at com.intellij.serviceContainer.PlatformComponentManagerImpl.instantiateClassWithConstructorInjection(PlatformComponentManagerImpl.kt:567)
	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:55)
	at com.intellij.serviceContainer.ServiceComponentAdapter.access$createAndInitialize(ServiceComponentAdapter.kt:15)
	at com.intellij.serviceContainer.ServiceComponentAdapter$doCreateInstance$$inlined$use$lambda$1.run(ServiceComponentAdapter.kt:47)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:600)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:546)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:183)
	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:46)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:113)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:69)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:62)
	at com.intellij.serviceContainer.PlatformComponentManagerImpl.doGetService(PlatformComponentManagerImpl.kt:343)
	at com.intellij.serviceContainer.PlatformComponentManagerImpl.getService(PlatformComponentManagerImpl.kt:330)
	at com.intellij.openapi.actionSystem.ActionManager.getInstance(ActionManager.java:28)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.actions.impl.ActionComponentImpl$manager$2.invoke(ActionComponentImpl.kt:30)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.actions.impl.ActionComponentImpl$manager$2.invoke(ActionComponentImpl.kt:29)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.dependencies.kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.actions.impl.ActionComponentImpl.getManager(ActionComponentImpl.kt)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.actions.impl.ActionComponentImpl.initComponent(ActionComponentImpl.kt:37)
	at com.intellij.serviceContainer.MyComponentAdapter.doCreateInstance(MyComponentAdapter.kt:46)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:113)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:69)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:62)
	at com.intellij.serviceContainer.PlatformComponentManagerImpl.createComponents(PlatformComponentManagerImpl.kt:220)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$loadComponents$3(ApplicationImpl.java:316)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:162)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:600)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:546)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:149)
	at com.intellij.openapi.application.impl.ApplicationImpl.loadComponents(ApplicationImpl.java:316)
	at com.intellij.idea.ApplicationLoader$startApp$6$loadComponentInEdtFuture$1.run(ApplicationLoader.kt:199)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:407)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by Sheigutn** [comment] 2020-02-12 17:46
Issue seems to be caused by the now deprecated plugin components: https://github.com/Hannah-Sten/TeXiFy-IDEA/issues/1141#issuecomment-567881896

**Comment by Russia9** [comment] 2020-02-13 20:52
Same thing in GoLand 2020.1 EAP: https://gist.github.com/Russia9/a3ec25c2b1698675fce8859867d89d0e

**Comment by Almighty-Alpaca** [comment] 2020-02-15 12:13
I've already looked a bit at the changes that come with 2020.1. Looks like they'll require quite a bit of work than I initially thought.

Thanks for reporting :+1:

**Comment by Almighty-Alpaca** [comment] 2020-04-13 15:07
A fix for this has already been pushed and will hopefully be released together with a few other improvements for 2020.1 sometime this week.

**Comment by Almighty-Alpaca** [comment] 2020-04-20 18:58
This bug has been fixed in v1.2.0 which is available on the JetBrains plugin repository as of this morning.

**Closed by Almighty-Alpaca** 2020-04-20 18:58 UTC

**Comment by jan4984** [comment] 2020-10-23 11:43
how to fix it in android studio? anyone

**Comment by Almighty-Alpaca** [comment] 2020-10-23 19:09
@jan4984 Which IntelliJ version do you use?

**Comment by jan4984** [comment] 2020-10-26 08:51
> @jan4984 Which IntelliJ version do you use?

I found that something wrong with my d-bus, after fixing, android stuiod start in normal.
