### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by uRyanxD** [Almighty-Alpaca/JetBrains-Discord-Integration#170] opened 2021-06-30 15:44 UTC
Hi, I'm trying to use the plugin on Intellij IDEA Community Edition 2021.2 EAP, but I'm getting this error:

```java
Plugin 'com.almightyalpaca.intellij.plugins.discord' failed to initialize and will be disabled. Please restart IntelliJ IDEA.

java.lang.ClassNotFoundException: 
                com.almightyalpaca.jetbrains.plugins.discord.plugin.development.DisableDynamicPluginComponent
             PluginClassLoader(plugin=PluginDescriptor(name=Discord Integration, id=com.almightyalpaca.intellij.plugins.discord, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\IdeaIC2021.2\plugins\plugin, version=1.6.1, package=null), packagePrefix=null, instanceId=28, state=active)
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:254)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
    at com.intellij.serviceContainer.ComponentManagerImpl.registerComponent(ComponentManagerImpl.kt:441)
    at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:380)
    at com.intellij.serviceContainer.ComponentManagerImpl.access$registerComponents(ComponentManagerImpl.kt:58)
    at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:255)
    at com.intellij.openapi.client.ClientAwareComponentManager.registerComponents(ClientAwareComponentManager.kt:62)
    at com.intellij.idea.ApplicationLoader$initApplication$2$1.accept(ApplicationLoader.kt:77)
    at com.intellij.idea.ApplicationLoader$initApplication$2$1.accept(ApplicationLoader.kt)
    at java.base/java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:753)
    at java.base/java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:731)
    at java.base/java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2108)
    at com.intellij.idea.ApplicationLoader$initApplication$2.apply(ApplicationLoader.kt:75)
    at com.intellij.idea.ApplicationLoader$initApplication$2.apply(ApplicationLoader.kt)
    at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072)
    at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
    at com.intellij.idea.ApplicationLoader$initApplication$3.execute(ApplicationLoader.kt:107)
    at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1118)
    at java.base/java.util.concurrent.CompletableFuture.thenComposeAsync(CompletableFuture.java:2246)
    at java.base/java.util.concurrent.CompletableFuture.thenComposeAsync(CompletableFuture.java:143)
    at com.intellij.idea.ApplicationLoader.initApplication(ApplicationLoader.kt:65)
    at com.a.b.a.d.ae.a(ae.java:62)
    at com.a.b.a.d.aL.a(aL.java:119)
    at com.a.b.a.d.a8.a(a8.java:310)
    at com.a.b.a.d.a8.b(a8.java:143)
    at com.a.b.a.d.a8.a(a8.java:93)
    at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
    at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
    at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1705)
    at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
    at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
    at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
    at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
    at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
    at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by InfRandomness** [comment] 2021-06-30 15:53
Hi, please to try to switch to the EAP channel using those instructions : 
0) Open your IDE
1) Go to Settings > Plugins
2) Click on the gear icon at the top
3) Select Manage Plugin Repositories...
4) Click add in the top right corner
5) Paste this link https://plugins.jetbrains.com/plugins/eap/10233
6) If the update isn't displayed immediately close the settings and click on Help > Check for updates...

There is an issue currently due to a recent PR that has been made, the fix is on the development branch (which is released on the EAP channel)

**Comment by Almighty-Alpaca** [comment] 2021-06-30 15:59
Duplicate of #158

**Closed by Almighty-Alpaca** 2021-06-30 15:59 UTC
Labels: area: plugin, state: duplicate, type: bug
