### ISSUE TITLE
Exception in Plugin Discord Integration

### ISSUE THREAD

**Issue by hyprex-deva** [Almighty-Alpaca/JetBrains-Discord-Integration#256] opened 2022-12-03 08:18 UTC
The Plugin is not working, and showing some errors
<img width="960" alt="image" src="https://user-images.githubusercontent.com/96543076/205431596-79c26e79-3dff-4d8a-a330-0559a9e985a4.png">

**Comment by Sewer56** [comment] 2022-12-03 08:32
This is a duplicate of https://github.com/Almighty-Alpaca/JetBrains-Discord-Integration/issues/244#issuecomment-1295903132

**Comment by hyprex-deva** [comment] 2022-12-03 10:01
I did this just now and tried to force reconnect.
![image](https://user-images.githubusercontent.com/96543076/205435084-845b38b6-9c43-4fbd-88cf-4989a549e2fc.png)
It was not showing any errors but It was not working. After I did a restart it started showing this error.
![image](https://user-images.githubusercontent.com/96543076/205435285-435bb426-0554-44a2-a2ff-e47567dda7dc.png)

**Comment by 000rosiu** [comment] 2022-12-03 11:20
Same for me.

![Zrzut ekranu 2022-12-03 122010](https://user-images.githubusercontent.com/73873042/205438401-cd56572f-fca7-49a7-92c5-c2cdca342918.png)

**Comment by zAlyson** [comment] 2022-12-03 11:59
Same for me as well. Upgrade Intellij and it started to happen.

**Comment by 000rosiu** [comment] 2022-12-03 13:39
The problem is that I have the latest version of IntelliJ.
I will wait for the next IntelliJ update.

**Comment by hyprex-deva** [comment] 2022-12-03 18:06
Please fix the bug in the plugin and make it compatible with the Latest version of IntelliJ.

**Comment by fzbian** [comment] 2022-12-03 22:33
the same thing happened to me, I just updated to the latest version and the same error occurred.
![image](https://user-images.githubusercontent.com/66271721/205464433-97ed10c3-3870-419a-82f0-fec20c52f745.png)

**Comment by nottyl** [comment] 2022-12-04 07:45
I still have the same issue after accessing the EAP version. Both **Force Render Update** and **Force Reconnect** shows error. 
```
java.lang.Throwable: IPC error: ErrorEventData(code=4000, message=child "activity" fails because [child "state" fails because ["state" is not allowed to be empty]])
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:202)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.connection.DiscordIpcConnection.onError(DiscordIpcConnection.kt:93)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.connection.DiscordIpcConnection.access$onError(DiscordIpcConnection.kt:39)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.connection.DiscordIpcConnection$ipcClient$1$1.invokeSuspend$onError(DiscordIpcConnection.kt:47)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.connection.DiscordIpcConnection$ipcClient$1$1.access$invokeSuspend$onError(DiscordIpcConnection.kt)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.connection.DiscordIpcConnection$ipcClient$1$1$2.invoke(DiscordIpcConnection.kt:47)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.connection.DiscordIpcConnection$ipcClient$1$1$2.invoke(DiscordIpcConnection.kt:47)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.connection.DiscordIpcConnection$ipcClient$1$1$invokeSuspend$$inlined$onEvent$4$1.invokeSuspend(KDiscordIPC.kt:103)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

**Comment by Celesica** [comment] 2022-12-04 09:23
Hello, I'm having similar error with IntelliJ Ultimate 2022.3, WebStorm 2022.3, and PyCharm 2022.3

![image](https://user-images.githubusercontent.com/10039521/205483258-1e00255d-09e0-45b4-9968-e10514afdf07.png)

**Comment by 000rosiu** [comment] 2022-12-05 07:38
On my PyCharm 2022.3 plugin works correctly.

**Comment by hyprex-deva** [comment] 2022-12-06 10:33
> On my PyCharm 2022.3 plugin works correctly.

How did it get fixed??

**Comment by 000rosiu** [comment] 2022-12-06 14:36
> > On my PyCharm 2022.3 plugin works correctly.
> 
> 
> 
> How did it get fixed??

It worked normally for me all the time, and it still is unlike IntelliJ.

**Closed** 2023-10-31 19:24 UTC
