### ISSUE TITLE
Class cannot be cast to runnable

### ISSUE THREAD

**Issue by duncte123** [Almighty-Alpaca/JetBrains-Discord-Integration#197] opened 2021-09-05 16:38 UTC
Runnining on Ubuntu 20.04 LTS in Intellij 2021.2.1
Plugin version: 1.7.0+3

```
java.lang.ClassCastException: class com.almightyalpaca.jetbrains.plugins.discord.plugin.utils.AsyncKt$invokeOnEventThread$$inlined$invokeWithin$1 cannot be cast to class java.lang.Runnable (com.almightyalpaca.jetbrains.plugins.discord.plugin.utils.AsyncKt$invokeOnEventThread$$inlined$invokeWithin$1 is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @1859946b; java.lang.Runnable is in module java.base of loader 'bootstrap')
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.utils.AsyncKt.invokeOnEventThread(async.kt:47)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.data.DataService.getDataInternal(DataService.kt:83)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.data.DataService.getData(DataService.kt:53)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.render.RenderService$render$2.invokeSuspend(RenderService.kt:62)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by Almighty-Alpaca** [comment] 2021-09-05 18:04
Duplicate of #196

**Closed by Almighty-Alpaca** 2021-09-05 18:04 UTC
