### ISSUE TITLE
Apple Silicon support

### ISSUE THREAD

**Issue by vlourme** [Almighty-Alpaca/JetBrains-Discord-Integration#145] opened 2021-01-19 09:28 UTC
Hi, the plugin crash on new Apple Silicon SoC. Here is a log:

```
java.lang.UnsatisfiedLinkError: /Users/vico/Library/Caches/JetBrains/PhpStorm2020.3/tmp/jna4569697145745322662.tmp: dlopen(/Users/vico/Library/Caches/JetBrains/PhpStorm2020.3/tmp/jna4569697145745322662.tmp, 1): no suitable image found.  Did find:
	/Users/vico/Library/Caches/JetBrains/PhpStorm2020.3/tmp/jna4569697145745322662.tmp: no matching architecture in universal wrapper
	/Users/vico/Library/Caches/JetBrains/PhpStorm2020.3/tmp/jna4569697145745322662.tmp: no matching architecture in universal wrapper
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2442)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2498)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2694)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2627)
	at java.base/java.lang.Runtime.load0(Runtime.java:768)
	at java.base/java.lang.System.load(System.java:1837)
	at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:947)
	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:922)
	at com.sun.jna.Native.<clinit>(Native.java:190)
	at com.sun.jna.Pointer.<clinit>(Pointer.java:54)
	at com.sun.jna.Structure.<clinit>(Structure.java:2131)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.RpcService.update(RpcService.kt:121)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.RpcService.update$default(RpcService.kt:77)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.render.RenderService$render$2.invokeSuspend(RenderService.kt:75)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

java.lang.NoClassDefFoundError: Could not initialize class com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.connection.NativeRpcConnection
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.RpcService.update(RpcService.kt:121)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.RpcService.update$default(RpcService.kt:77)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.render.RenderService$render$2.invokeSuspend(RenderService.kt:75)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

PC Info:
- MacBook Pro M1
- PHPStorm 2020.3
- MacOS Big Sur 11.0.1

Important note: I don't have Rosseta installed since PHPStorm 2020.3 support natively Apple Silicon, I think this is the cause of the error: `no matching architecture in universal wrapper`.

Thank you, if you need any more details, feel free to ask me.

**Comment by InfRandomness** [comment] 2021-01-19 09:44
Hello, this looks related to https://github.com/discord/discord-api-docs/issues/1285, unfortunately we cannot do much about this until discord fixes this issue on their end, or until https://github.com/Almighty-Alpaca/JetBrains-Discord-Integration/pull/130 is merged

**Comment by foundbypass** [comment] 2021-06-23 17:14
Hello,
Are you still looking into this? :)

**Comment by cbyrneee** [comment] 2021-06-23 17:14
> Hello,
> Are you still looking into this? :)

Yes, I have made a pull request (#166) which resolves this issue

**Comment by cbyrneee** [comment] 2021-06-24 21:01
My pull request (#166) has been merged and this will be fixed in the next version of the plugin 🎉

**Comment by Almighty-Alpaca** [comment] 2021-06-24 21:28
There's an EAP build with the PR that should probably be approved tomorrow by JetBrains. To get EAP builds you have to follow these steps:

0) Open your IDE
1) Go to Settings > Plugins
2) Click on the gear icon at the top
3) Select _Manage Plugin Repositories..._
4) Click add in the top right corner
5) Paste this link <https://plugins.jetbrains.com/plugins/eap/10233>
6) If the update isn't displayed immediately close the settings and click on _Help > Check for updates..._

Feel free to leave some feedback here so I can release it for everyone as soon as possible.

**Comment by foundbypass** [comment] 2021-06-24 23:44
Hey,
Tried the EAP build and this is the error im getting now:

Unhandled exception in ***@***.***,
Dispatchers.Default]

java.lang.NoClassDefFoundError: Could not initialize class
com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.connection.NativeRpcConnection
at
com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.RpcService.update(RpcService.kt:121)
at
com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.RpcService.update$default(RpcService.kt:77)
at
com.almightyalpaca.jetbrains.plugins.discord.plugin.render.RenderService$render$2.invokeSuspend(RenderService.kt:75)
at
kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at
kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
at
kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
at
kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
at
kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

Den tors 24 juni 2021 kl 23:28 skrev Aljoscha Grebe <
***@***.***>:

**Comment by cbyrneee** [comment] 2021-06-25 09:54
Hi @foundbypass, from what I can see the update with M1 support isn't on the EAP builds yet. It should be up sometime today though

**Comment by Almighty-Alpaca** [comment] 2021-06-25 15:34
EAP version has just been approved 🎉

**Comment by Indiance** [comment] 2021-06-28 06:07
It still gives me the same error 😢

**Comment by cbyrneee** [comment] 2021-06-28 09:37
> It still gives me the same error 😢
@Indiance 

That shouldn't be the case. What version of the plugin are you currently running?

**Comment by Indiance** [comment] 2021-06-28 10:08
> > It still gives me the same error 😢
> > @Indiance
> 
> That shouldn't be the case. What version of the plugin are you currently running?

The one thats on the store. I think thats 1.6.1 
<img width="394" alt="Screenshot 2021-06-28 at 3 37 55 PM" src="https://user-images.githubusercontent.com/44136022/123619511-e064ee80-d826-11eb-9280-0a24e65b26e4.png">

**Comment by cbyrneee** [comment] 2021-06-28 11:07
@Indiance you need to use the EAP build of the plugin, you an see more information about it [here](https://github.com/Almighty-Alpaca/JetBrains-Discord-Integration/issues/145#issuecomment-867963445)

**Comment by Indiance** [comment] 2021-06-28 11:56
> @Indiance you need to use the EAP build of the plugin, you an see more information about it [here](https://github.com/Almighty-Alpaca/JetBrains-Discord-Integration/issues/145#issuecomment-867963445)

Yup this works

**Comment by XWX-Unknown-XWX** [comment] 2021-07-14 16:48
Hi! I've tried to add a link, but nothing changed!
I've got this problem:

Error while updating presence

java.lang.RuntimeException: java.net.SocketException: Connection refused
	at com.jagrosh.discordipc.entities.pipe.Pipe.createPipe(Pipe.java:145)
	at com.jagrosh.discordipc.entities.pipe.Pipe.openPipe(Pipe.java:59)
	at com.jagrosh.discordipc.IPCClient.connect(IPCClient.java:118)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.connection.DiscordIpcConnection.connect(DiscordIpcConnection.kt:55)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.RpcService$update$1.invokeSuspend(RpcService.kt:125)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: java.net.SocketException: Connection refused
	at org.newsclub.net.unix.NativeUnixSocket.connect(Native Method)
	at org.newsclub.net.unix.AFUNIXSocketImpl.connect(AFUNIXSocketImpl.java:264)
	at org.newsclub.net.unix.AFUNIXSocket.connect(AFUNIXSocket.java:156)
	at org.newsclub.net.unix.AFUNIXSocket.connect(AFUNIXSocket.java:125)
	at com.jagrosh.discordipc.entities.pipe.UnixPipe.<init>(UnixPipe.java:39)
	at com.jagrosh.discordipc.entities.pipe.Pipe.createPipe(Pipe.java:143)
	... 10 more

**Comment by cbyrneee** [comment] 2021-07-14 18:15
That's a weird one, @XWX-Unknown-XWX. Is the discord client open when this error occurs?

**Comment by XWX-Unknown-XWX** [comment] 2021-07-14 18:40
Yep

**Comment by XWX-Unknown-XWX** [comment] 2021-07-14 18:45
No, It isn't open

Looks like it is my bad 😣

**Comment by cbyrneee** [comment] 2021-07-14 19:19
I thought that issue was fixed, maybe it wasn't. I'll contact Alpaca to see what's happening

**Comment by punctuations** [comment] 2021-07-20 04:26
> I thought that issue was fixed, maybe it wasn't. I'll contact Alpaca to see what's happening

I added the plugin repository and mine's working flawlessly! (Macbook was also bought about a month ago)
![image](https://user-images.githubusercontent.com/37005919/126261797-f5dc3de1-ae8e-41c0-9ae7-8c1b3bcf9158.png)

**Comment by XWX-Unknown-XWX** [comment] 2021-07-20 08:09
That's rly strange, because I did the same thing, and as the result, when my Discord is off, I see this (I bought for about 2 weeks ago, but I don't think this playing smth in this issue): 
<img width="858" alt="Screenshot 2021-07-20 at 11 07 59" src="https://user-images.githubusercontent.com/73190129/126285152-d378daec-1828-4921-b725-8fe3c6ed9d0f.png">

**Comment by Almighty-Alpaca** [comment] 2021-07-20 08:11
I've pushed a fix for this out on the weekend, but it hasn't been approved by JetBrains yet. They'll probably get to do that today.

**Comment by XWX-Unknown-XWX** [comment] 2021-07-20 14:44
New version has been approved by JetBrains!!! 🥳🥳🥳

Now it works perfect!!! Thanks @Almighty-Alpaca!!!
<img width="287" alt="Screenshot 2021-07-20 at 17 43 55" src="https://user-images.githubusercontent.com/73190129/126344298-d2709b9b-c85f-4e07-8dcf-1a3a375f9961.png">

**Comment by Almighty-Alpaca** [comment] 2021-07-27 12:37
This is now on stable v1.7.0 🥳

**Closed by Almighty-Alpaca** 2021-07-27 12:37 UTC
Labels: area: plugin, state: waiting for release, type: bug
