### ISSUE TITLE
Feature: custom title

### ISSUE THREAD

**Issue by Roboroads** [Almighty-Alpaca/JetBrains-Discord-Integration#215] opened 2022-02-14 11:34 UTC
I think "plays Writing Code" is nicer than "plays PhpStorm". I would like to request to be able to customize that part as well.

**Comment by Almighty-Alpaca** [comment] 2022-02-14 11:42
Unfortunately this is not possible due to how Discord works. Closing this as duplicate of #114

**Closed by Almighty-Alpaca** 2022-02-14 11:42 UTC
Labels: state: duplicate, type: feature, area: plugin
