### ISSUE TITLE
Discord Integration not Working

### ISSUE THREAD

**Issue by xFedeT** [Almighty-Alpaca/JetBrains-Discord-Integration#231] opened 2022-06-26 08:55 UTC
> I currently am having this issue. Reinstalling discord did not fix the issue. Spotify integration, Lunar client integration, and all other RPC connections function as intended.

Same

_Originally posted by @xFedeT in https://github.com/Almighty-Alpaca/JetBrains-Discord-Integration/issues/11#issuecomment-1166459050_

**Comment by xFedeT** [comment] 2022-06-26 09:01
@Almighty-Alpaca 
``` Cannot create listener

com.intellij.diagnostic.PluginException: Cannot create listener com.almightyalpaca.jetbrains.plugins.discord.plugin.time.TimeDynamicPluginListener [Plugin: com.almightyalpaca.intellij.plugins.discord]
	at com.intellij.serviceContainer.ComponentManagerImpl.createListener(ComponentManagerImpl.kt:920)
	at com.intellij.util.messages.impl.CompositeMessageBus.subscribeLazyListeners(CompositeMessageBus.java:177)
	at com.intellij.util.messages.impl.CompositeMessageBus.doComputeSubscribers(CompositeMessageBus.java:147)
	at com.intellij.util.messages.impl.MessageBusImpl.computeSubscribers(MessageBusImpl.java:349)
	at com.intellij.util.messages.impl.CompositeMessageBus.computeSubscribers(CompositeMessageBus.java:141)
	at com.intellij.util.messages.impl.CompositeMessageBus$ToDirectChildrenMessagePublisher.lambda$publish$0(CompositeMessageBus.java:103)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at com.intellij.util.messages.impl.CompositeMessageBus$ToDirectChildrenMessagePublisher.publish(CompositeMessageBus.java:103)
	at com.intellij.util.messages.impl.MessageBusImpl$MessagePublisher.invoke(MessageBusImpl.java:167)
	at com.sun.proxy.$Proxy180.checkUnloadPlugin(Unknown Source)
	at com.intellij.ide.plugins.DynamicPlugins.checkCanUnloadWithoutRestart(DynamicPlugins.kt:229)
	at com.intellij.ide.plugins.DynamicPlugins.checkCanUnloadWithoutRestart$default(DynamicPlugins.kt:196)
	at com.intellij.ide.plugins.DynamicPlugins.allowLoadUnloadWithoutRestart(DynamicPlugins.kt:102)
	at com.intellij.ide.plugins.DynamicPlugins.allowLoadUnloadWithoutRestart$default(DynamicPlugins.kt:101)
	at com.intellij.ide.plugins.DynamicPlugins.allowLoadUnloadWithoutRestart(DynamicPlugins.kt)
	at com.intellij.ide.plugins.PluginInstallOperation.prepareToInstall(PluginInstallOperation.java:266)
	at com.intellij.ide.plugins.PluginInstallOperation.prepareToInstallWithCallback(PluginInstallOperation.java:225)
	at com.intellij.ide.plugins.PluginInstallOperation.prepareToInstall(PluginInstallOperation.java:198)
	at com.intellij.ide.plugins.PluginInstallOperation.run(PluginInstallOperation.java:138)
	at com.intellij.ide.plugins.newui.MyPluginModel.runInstallOperation(MyPluginModel.java:441)
	at com.intellij.ide.plugins.newui.MyPluginModel$1.run(MyPluginModel.java:409)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:442)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$5(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:244)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:189)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:244)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.ClassNotFoundException: com.almightyalpaca.jetbrains.plugins.discord.plugin.time.TimeDynamicPluginListener PluginClassLoader(plugin=PluginDescriptor(name=Discord Integration, id=com.almightyalpaca.intellij.plugins.discord, descriptorPath=plugin.xml, path=~\AppData\Local\JetBrains\Toolbox\apps\WebStorm\ch-0\221.5080.193.plugins\JetBrains-Discord-Integration, version=1.9.0, package=null, isBundled=false), packagePrefix=null, instanceId=112, state=active)
	at com.intellij.serviceContainer.ComponentManagerImplKt.doLoadClass(ComponentManagerImpl.kt:1469)
	at com.intellij.serviceContainer.ComponentManagerImplKt.access$doLoadClass(ComponentManagerImpl.kt:1)
	at com.intellij.serviceContainer.ComponentManagerImpl.createListener(ComponentManagerImpl.kt:917)
	... 40 more
```

**Comment by Loremente** [comment] 2022-06-26 11:37
Vai su discord togli l'opzione Mostra le attività in corso come messaggio di stato e così la gente si farà i cazzi propri e tu vivrai sereno

**Comment by InfRandomness** [comment] 2022-06-26 11:56
Would it be possible to keep it English ? Thanks

**Comment by Loremente** [comment] 2022-06-26 12:01
sorry

**Comment by xFedeT** [comment] 2022-06-26 12:03
> Would it be possible to keep it English ? Thanks

The funny guy Loremente wrote: "Go to discord remove the option Show the activities in progress as a status message and so people will have their own cocks and you will live peacefully"

**Comment by Loremente** [comment] 2022-06-26 12:04
It's the reallity 😔

**Comment by xFedeT** [comment] 2022-06-26 12:09
@Almighty-Alpaca Can you Kick Loremente from this discussion? please

**Comment by InfRandomness** [comment] 2022-06-26 12:10
Duplicate of #225

**Comment by xFedeT** [comment] 2022-06-26 12:11
Thanks, but how i can Fix it?

**Closed** 2022-06-26 12:10 UTC

**Comment by InfRandomness** [comment] 2022-06-26 12:13
> Thanks, but how i can Fix it?

Wait until the PR is merged and a version of the plugin with the fix is released

**Comment by AustinNick** [comment] 2023-09-11 06:43
i have this problem too
```

java.lang.Throwable: IPC error: ErrorEventData(code=4000, message=child "activity" fails because [child "assets" fails because [child "large_text" fails because ["large_text" is not allowed to be empty]]])
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:370)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.connection.DiscordIpcConnection.onError(DiscordIpcConnection.kt:133)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.connection.DiscordIpcConnection.access$onError(DiscordIpcConnection.kt:39)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.connection.DiscordIpcConnection$ipcClient$1$1.invokeSuspend$onError(DiscordIpcConnection.kt:47)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.connection.DiscordIpcConnection$ipcClient$1$1.access$invokeSuspend$onError(DiscordIpcConnection.kt)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.connection.DiscordIpcConnection$ipcClient$1$1$2.invoke(DiscordIpcConnection.kt:47)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.connection.DiscordIpcConnection$ipcClient$1$1$2.invoke(DiscordIpcConnection.kt:47)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.connection.DiscordIpcConnection$ipcClient$1$1$invokeSuspend$$inlined$onEvent$4$1.invokeSuspend(KDiscordIPC.kt:103)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:100)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)

```
