### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by Skjolberg** [Almighty-Alpaca/JetBrains-Discord-Integration#320] opened 2023-02-15 13:27 UTC
I have been getting different errors, although this is one of them.

![](https://i.ibb.co/P6Hs5wq/Discord-Plugin-Intellij.png)

My config (Application):
![](https://i.gyazo.com/3f90461f1d83fccb777350c856eda2e8.png)

(Project):
![](https://i.gyazo.com/e8e784a981645f0b5b123be4c80c1723.png)

(File):
![](https://i.gyazo.com/0c9bcf894dc4b0d3452360ada3c0413f.png)

**Comment by dnbln** [comment] 2023-02-15 13:55
Duplicate of #250

**Closed by dnbln** 2023-02-15 13:55 UTC
