### ISSUE TITLE
Exception in plugin Discord Integration (1.9.0)

### ISSUE THREAD

**Issue by tommytim0515** [Almighty-Alpaca/JetBrains-Discord-Integration#235] opened 2022-07-13 08:33 UTC
Really appreciate you for making such an awesome plugin. I love it so much!

The Exception:

```bash
Cannot create listener

com.intellij.diagnostic.PluginException: Cannot create listener com.almightyalpaca.jetbrains.plugins.discord.plugin.time.TimeDynamicPluginListener [Plugin: com.almightyalpaca.intellij.plugins.discord]
Caused by: java.lang.ClassNotFoundException: com.almightyalpaca.jetbrains.plugins.discord.plugin.time.TimeDynamicPluginListener PluginClassLoader(plugin=PluginDescriptor(name=Discord Integration, id=com.almightyalpaca.intellij.plugins.discord, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/Toolbox/apps/Goland/ch-0/221.5921.26/GoLand.app.plugins/JetBrains-Discord-Integration, version=1.9.0, package=null, isBundled=false), packagePrefix=null, instanceId=117, state=active)
	at com.intellij.serviceContainer.ComponentManagerImplKt.doLoadClass(ComponentManagerImpl.kt:1469)
	at com.intellij.serviceContainer.ComponentManagerImplKt.access$doLoadClass(ComponentManagerImpl.kt:1)
	at com.intellij.serviceContainer.ComponentManagerImpl.createListener(ComponentManagerImpl.kt:917)
	at com.intellij.util.messages.impl.CompositeMessageBus.subscribeLazyListeners(CompositeMessageBus.java:177)
	at com.intellij.util.messages.impl.CompositeMessageBus.doComputeSubscribers(CompositeMessageBus.java:147)
	at com.intellij.util.messages.impl.MessageBusImpl.computeSubscribers(MessageBusImpl.java:349)
	at com.intellij.util.messages.impl.CompositeMessageBus.computeSubscribers(CompositeMessageBus.java:141)
	at com.intellij.util.messages.impl.CompositeMessageBus$ToDirectChildrenMessagePublisher.lambda$publish$0(CompositeMessageBus.java:103)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at com.intellij.util.messages.impl.CompositeMessageBus$ToDirectChildrenMessagePublisher.publish(CompositeMessageBus.java:103)
	at com.intellij.util.messages.impl.MessageBusImpl$MessagePublisher.invoke(MessageBusImpl.java:167)
	at com.sun.proxy.$Proxy185.checkUnloadPlugin(Unknown Source)
	at com.intellij.ide.plugins.DynamicPlugins.checkCanUnloadWithoutRestart(DynamicPlugins.kt:228)
	at com.intellij.ide.plugins.DynamicPlugins.checkCanUnloadWithoutRestart$default(DynamicPlugins.kt:195)
	at com.intellij.ide.plugins.DynamicPlugins.allowLoadUnloadWithoutRestart(DynamicPlugins.kt:101)
	at com.intellij.ide.plugins.DynamicPlugins.allowLoadUnloadWithoutRestart$default(DynamicPlugins.kt:100)
	at com.intellij.ide.plugins.DynamicPlugins.allowLoadUnloadWithoutRestart(DynamicPlugins.kt)
	at com.intellij.openapi.updateSettings.impl.PluginDownloader.installDynamically(PluginDownloader.java:340)
	at com.intellij.openapi.updateSettings.impl.PluginUpdateDialog$4.installPluginUpdates(PluginUpdateDialog.java:232)
	at com.intellij.openapi.updateSettings.impl.PluginUpdateDialog$4.lambda$run$0(PluginUpdateDialog.java:203)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:215)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:197)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:511)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:69)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:112)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:803)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

Happens quite often during the time I use Goland (e.g., when I open the IDE, and IDE reloads when I install some new plugins).

Platform: Macbook Air 2020 Apple Silicon M1
OS: macOS Monterey 12.4
Goland Version: 2022.1.3
Java Version:
```bash
java -version

openjdk version "18.0.1.1" 2022-04-22
OpenJDK Runtime Environment (build 18.0.1.1+2-6)
OpenJDK 64-Bit Server VM (build 18.0.1.1+2-6, mixed mode, sharing)
```

<img width="1457" alt="image" src="https://user-images.githubusercontent.com/44408451/178687944-f8885044-732d-4fbc-833e-8e639edf7e40.png">

**Comment by Almighty-Alpaca** [comment] 2022-08-06 11:19
Duplicate of #225

**Closed by Almighty-Alpaca** 2022-08-06 11:19 UTC
Labels: type: bug, state: duplicate, area: plugin
